var mission_list = new Array();
mission_list[0] = new Array('Tutorial','$100','$500','1','Defeat the enemy','Less than 5 turns','Battle.Money(100,"self");','Battle.Money(500,"self");','[x]','battlestats[2]<=4');
mission_list[1] = new Array('Tutorial','$100','$500','2','Defeat the enemy','Less than 5 turns','Battle.Money(100,"self");','Battle.Money(500,"self");','[x]','battlestats[2]<=4');
mission_list[2] = new Array('Tutorial','$100','$500','3','Defeat the enemy','Less than 5 turns','Battle.Money(100,"self");','Battle.Money(500,"self");','[x]','battlestats[2]<=4');
mission_list[3] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[4] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[5] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[6] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[7] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[8] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[9] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[10] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[11] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[12] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[13] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[14] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[15] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[16] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[17] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[18] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[19] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[20] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[21] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[22] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[23] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[24] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
mission_list[25] = new Array('Mission Name','Reward1','Ace Award','Enemy','Mission Brief','Ace Condition','rwd1cmd','rwd2cmd','[x]','acecnd');
