document.write('<span id="bmap" style="position:absolute;top:'+iconsize+';left:'+iconsize+';">')
document.write('<table cellpadding=0 border=0 cellspacing=0>');
for (a=1;a<=gridsize;a++){document.write('<tr>');
for (b=1;b<=gridsize;b++){document.write('<td style="border:1 solid white;cursor:hand;"><img src="res/skins/classic/13.png" height='+iconsize+' width='+iconsize+' id="g'+a+'x'+b+'b" style="z-index:1;" value=13 onclick="this.src=\'res/skins/classic/\'+brush_left+\'.png\';this.value=brush_left;" oncontextmenu="this.src=\'res/skins/classic/\'+brush_right+\'.png\';this.value=brush_right;" title="x='+b+' y='+a+'"></td>');}
document.write('</tr>');
}
document.write('</table></span>');
document.write('<span id="fmap" style="position:absolute;top:'+iconsize+';left:'+iconsize+';">')
document.write('<table cellpadding=0 border=0 cellspacing=0>');
for (a=1;a<=gridsize;a++){document.write('<tr>');
for (b=1;b<=gridsize;b++){document.write('<td style="border:1 solid white;cursor:hand;"><img src="res/skins/classic/0.png" height='+iconsize+' width='+iconsize+' id="g'+a+'x'+b+'f" style="z-index:2;" value=0 onclick="this.src=\'res/skins/classic/\'+brush_left+\'.png\';this.value=brush_left;" oncontextmenu="this.src=\'res/skins/classic/\'+brush_right+\'.png\';this.value=brush_right;" title="x='+b+' y='+a+'"></td>');}
document.write('</tr>');
}
document.write('</table></span>');

document.write('<input type="button" value="Reset" onclick="AskReset()" class="btn2" style="position:absolute;top:0;left:10;"><span style="position:absolute;top:530;left:30;"><b>Brushes: </b><img src="res/skins/classic/0.png" style="border:1 solid white;" id="lbrush"><img src="res/skins/classic/0.png" style="border:1 solid white;" id="rbrush">');
document.write('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>View:</b> <select onchange="eval(this.value);"><option value=\'bmap.style.display="block";fmap.style.display="none";\'>Background</option><option value=\'fmap.style.display="block";bmap.style.display="none";\' selected>Foreground</option><option value=\'bmap.style.display="block";fmap.style.display="block";\'>Both</option></select>');
document.write('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" class="btn2" value="Fill Map" onclick="FillMap()"> <img src="res/skins/classic/0.png" style="border:1 solid white;cursor:hand;" id="fill_color" value=0 onclick="this.src=\'res/skins/classic/\'+brush_left+\'.png\';this.value=brush_left;" oncontextmenu="this.src=\'res/skins/classic/\'+brush_right+\'.png\';this.value=brush_right;"><br><br>');
document.write('<img src="res/skins/classic/0.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(0)" oncontextmenu="NewRBrush(0)"><img src="res/skins/classic/1.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(1)" oncontextmenu="NewRBrush(1)"><img src="res/skins/classic/2.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(2)" oncontextmenu="NewRBrush(2)"><img src="res/skins/classic/3.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(3)" oncontextmenu="NewRBrush(3)">');
document.write('<img src="res/skins/classic/4.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(4)" oncontextmenu="NewRBrush(4)"><img src="res/skins/classic/5.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(5)" oncontextmenu="NewRBrush(5)"><img src="res/skins/classic/6.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(6)" oncontextmenu="NewRBrush(6)"><img src="res/skins/classic/7.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(7)" oncontextmenu="NewRBrush(7)">');
document.write('<img src="res/skins/classic/8.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(8)" oncontextmenu="NewRBrush(8)"><img src="res/skins/classic/9.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(9)" oncontextmenu="NewRBrush(9)"><img src="res/skins/classic/10.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(10)" oncontextmenu="NewRBrush(10)"><img src="res/skins/classic/11.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(11)" oncontextmenu="NewRBrush(11)">');
document.write('<img src="res/skins/classic/12.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(12)" oncontextmenu="NewRBrush(12)"><img src="res/skins/classic/13.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(13)" oncontextmenu="NewRBrush(13)"><img src="res/skins/classic/14.png" style="border:1 solid white;cursor:hand;" onclick="NewLBrush(14)" oncontextmenu="NewRBrush(14)"><br><br>');
document.write('<b>Player Start X:</b> <select id="p_x"><option value=1>1</option><option value=2>2</option><option value=3>3</option><option value=4>4</option><option value=5>5</option><option value=6>6</option><option value=7>7</option><option value=8>8</option><option value=9>9</option><option value=10>10</option><option value=11>11</option><option value=12>12</option><option value=13>13</option><option value=14>14</option><option value=15>15</option></select> ');
document.write('<b>Player Start Y:</b> <select id="p_y"><option value=1>1</option><option value=2>2</option><option value=3>3</option><option value=4>4</option><option value=5>5</option><option value=6>6</option><option value=7>7</option><option value=8>8</option><option value=9>9</option><option value=10>10</option><option value=11>11</option><option value=12>12</option><option value=13>13</option><option value=14>14</option><option value=15>15</option></select> ');
document.write('<b>Player Start Color:</b> <img src="res/skins/classic/1.png" id="p_color" value=1 onclick="this.src=\'res/skins/classic/\'+brush_left+\'.png\';this.value=brush_left;" oncontextmenu="this.src=\'res/skins/classic/\'+brush_right+\'.png\';this.value=brush_right;" style="border:1 solid white;cursor:hand;"><br><br><b>Gems Required:</b> <input type="textarea" id="r_gem" style="height:19;background-Color:navajowhite;border:1 solid white;width:40;" maxlength=3 onKeypress="if (event.keyCode < 45 || event.keyCode > 57) event.returnValue = false;" value=0>&nbsp;<b>Gems on Map:</b> <input type="textarea" id="t_gem" readonly value=0 style="height:19;background-Color:navajowhite;border:1 solid white;width:40;"> <input type="button" value="Count Gems" onclick="CountGems()" class="btn2"><br><br>');
document.write('<b>Music:</b><select id="c_music"><option value=-1 selected>Random</option><option value=1>Song 1</option><option value=2>Song 2</option><option value=3>Song 3</option><option value=4>Song 4</option><option value=5>Song 5</option><option value=6>Song 6</option><option value=7>Song 7</option><option value=8>Song 8</option><option value=9>Song 9</option></select> ');
document.write('<input type="button" value="Play" class="btn2" onclick="BG.src=\'res/music/\'+c_music.value+\'.mid\'"> <input type="button" value="Stop" class="btn2" onclick="BG.src=\'\'"><br><br><input type="button" value="Generate" onclick="CountGems(1)" class="btn2"> <input type="button" value="Save Map" onclick="SaveMap()" class="btn2" style="visibility:hidden;" id="btn_save"><span style="display:none;"><br><br><textarea id="small_vars"></textarea><textarea id="medium_vars"></textarea><textarea id="large_vars"></textarea><textarea id="master_vars" style="width:550;"></textarea></span></span>');